// <auto-generated />
using AdatbazisKapcsolat.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdatbazisKapcsolat.Migrations
{
    [DbContext(typeof(AdatbázisKapcsolat))]
    [Migration("20240909094817_sqlite.local_migration_859")]
    partial class sqlitelocal_migration_859
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("AdatbazisKapcsolat.Models.Felhasznalo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SzulEv")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Felhasznalok");
                });
#pragma warning restore 612, 618
        }
    }
}
